package version3;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alecco
 */
public class FrameUserInfo extends javax.swing.JFrame {

      /**
       * Creates new form FrameUserInfo
       */
      public FrameUserInfo() {
            initComponents();
            
            
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel6 = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            lblParkingLocation = new javax.swing.JLabel();
            btnX = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            popContent = new javax.swing.JPanel();
            UserInfo = new javax.swing.JPanel();
            jPanel6 = new javax.swing.JPanel();
            jLabel3 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jLabel7 = new javax.swing.JLabel();
            jPanel2 = new javax.swing.JPanel();
            txtName = new javax.swing.JLabel();
            txtPlateno = new javax.swing.JLabel();
            txtTimein = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();

            jLabel6.setText("jLabel6");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            setResizable(false);

            jPanel1.setBackground(new java.awt.Color(51, 255, 51));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lblParkingLocation.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
            lblParkingLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jPanel1.add(lblParkingLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

            btnX.setBackground(new java.awt.Color(255, 0, 0));

            jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("x");
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel2MouseExited(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel2MouseEntered(evt);
                  }
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout btnXLayout = new javax.swing.GroupLayout(btnX);
            btnX.setLayout(btnXLayout);
            btnXLayout.setHorizontalGroup(
                  btnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            );
            btnXLayout.setVerticalGroup(
                  btnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            );

            jPanel1.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

            popContent.setBackground(new java.awt.Color(0, 0, 0));
            popContent.setLayout(new java.awt.CardLayout());

            UserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel6.setBackground(new java.awt.Color(51, 51, 51));

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("CANCEL");
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel3MouseExited(evt);
                  }
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel3MouseClicked(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel3MouseEntered(evt);
                  }
            });

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 135, Short.MAX_VALUE)
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
            );
            jPanel6Layout.setVerticalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 40, Short.MAX_VALUE)
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            UserInfo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 150, 135, 40));

            jPanel5.setBackground(new java.awt.Color(51, 255, 51));

            jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("TIME OUT");
            jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel7MouseExited(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel7MouseEntered(evt);
                  }
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel7MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            );
            jPanel5Layout.setVerticalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            );

            UserInfo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 135, 40));

            jPanel2.setBackground(new java.awt.Color(0, 0, 0));
            jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            txtName.setForeground(new java.awt.Color(255, 255, 255));
            jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 200, 30));

            txtPlateno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            txtPlateno.setForeground(new java.awt.Color(255, 255, 255));
            jPanel2.add(txtPlateno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 30));

            txtTimein.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            txtTimein.setForeground(new java.awt.Color(255, 255, 255));
            jPanel2.add(txtTimein, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 200, 30));

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Time-in:");
            jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 70, 30));

            jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(255, 255, 255));
            jLabel8.setText("Plate No:");
            jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

            jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setText("Name:");
            jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 60, 30));

            UserInfo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

            popContent.add(UserInfo, "card5");

            jPanel1.add(popContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 200));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setBounds((screenSize.width-300)/2, (screenSize.height-250)/2, 300, 250);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
            jLabel2.setForeground(Color.WHITE);
            btnX.setBackground(new Color(51, 51, 51));
      }//GEN-LAST:event_jLabel2MouseEntered
      private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            dispose();
      }//GEN-LAST:event_jLabel2MouseClicked
      private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
            jLabel2.setForeground(Color.WHITE);
            btnX.setBackground(Color.RED);
      }//GEN-LAST:event_jLabel2MouseExited
      private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
            mouseHover(jPanel5, jLabel7);
      }//GEN-LAST:event_jLabel7MouseEntered
      private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
            jLabel7.setForeground(Color.BLACK);
            jPanel5.setBackground(new Color(51,255,51));
      }//GEN-LAST:event_jLabel7MouseExited
      private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            String loc = lblParkingLocation.getText();
            MyInstantiation.buttonDisabler(loc);
            
            dispose();
      }//GEN-LAST:event_jLabel7MouseClicked
      private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
            dispose();
      }//GEN-LAST:event_jLabel3MouseClicked
      private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
            mouseHover(jPanel6, jLabel3);
      }//GEN-LAST:event_jLabel3MouseEntered

      private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
            mouseHover(jLabel3, jPanel6);
      }//GEN-LAST:event_jLabel3MouseExited

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(FrameUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(FrameUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(FrameUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(FrameUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new FrameUserInfo().setVisible(true);
                  }
            });
      }
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JPanel UserInfo;
      private javax.swing.JPanel btnX;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel5;
      private javax.swing.JPanel jPanel6;
      public static javax.swing.JLabel lblParkingLocation;
      private javax.swing.JPanel popContent;
      public static javax.swing.JLabel txtName;
      public static javax.swing.JLabel txtPlateno;
      public static javax.swing.JLabel txtTimein;
      // End of variables declaration//GEN-END:variables
      public void mouseHover(JPanel p, JLabel l) {
            //entered
            l.setForeground(Color.WHITE);
            p.setBackground(new Color(233, 87, 63));
      }
      public void mouseHover(JLabel l, JPanel p) {
            //exit
            l.setForeground(Color.WHITE);
            p.setBackground(new Color(51, 51, 51));
      }
      
      public static void locationListener(String q){
            lblParkingLocation.setText(q);
      }
      
      
}
