package version3;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class FramePopup extends javax.swing.JFrame {


      public FramePopup() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            lblParkingLocation = new javax.swing.JLabel();
            btnX = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            popContent = new javax.swing.JPanel();
            PopMessage = new javax.swing.JPanel();
            jPanel7 = new javax.swing.JPanel();
            jLabel10 = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);

            jPanel1.setBackground(new java.awt.Color(51, 255, 51));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lblParkingLocation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
            lblParkingLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jPanel1.add(lblParkingLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

            btnX.setBackground(new java.awt.Color(255, 0, 0));

            jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("x");
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel2MouseExited(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel2MouseEntered(evt);
                  }
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout btnXLayout = new javax.swing.GroupLayout(btnX);
            btnX.setLayout(btnXLayout);
            btnXLayout.setHorizontalGroup(
                  btnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            );
            btnXLayout.setVerticalGroup(
                  btnXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            );

            jPanel1.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

            popContent.setBackground(new java.awt.Color(0, 0, 0));
            popContent.setLayout(new java.awt.CardLayout());

            PopMessage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel7.setBackground(new java.awt.Color(51, 255, 51));

            jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setText("OK");
            jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel10MouseExited(evt);
                  }
                  public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel10MouseEntered(evt);
                  }
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel10MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                  jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            );
            jPanel7Layout.setVerticalGroup(
                  jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            );

            PopMessage.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 150, 135, 40));

            jPanel3.setBackground(new java.awt.Color(0, 0, 0));

            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Time-in Successful");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addContainerGap(106, Short.MAX_VALUE))
            );

            PopMessage.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

            popContent.add(PopMessage, "card3");

            jPanel1.add(popContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 200));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setBounds((screenSize.width-300)/2, (screenSize.height-250)/2, 300, 250);
      }// </editor-fold>//GEN-END:initComponents

      private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
            jLabel2.setForeground(Color.WHITE);
            btnX.setBackground(Color.RED);
      }//GEN-LAST:event_jLabel2MouseExited

      private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
            jLabel2.setForeground(Color.WHITE);
            btnX.setBackground(new Color(51, 51, 51));
      }//GEN-LAST:event_jLabel2MouseEntered

      private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            System.exit(1);
      }//GEN-LAST:event_jLabel2MouseClicked

      private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
            jLabel10.setForeground(Color.BLACK);
            jPanel7.setBackground(new Color(51,255,51));
      }//GEN-LAST:event_jLabel10MouseExited

      private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
            mouseHover(jPanel7, jLabel10);
      }//GEN-LAST:event_jLabel10MouseEntered

      private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
            dispose();
      }//GEN-LAST:event_jLabel10MouseClicked

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(FramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(FramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(FramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(FramePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new FramePopup().setVisible(true);
                  }
            });
      }
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JPanel PopMessage;
      private javax.swing.JPanel btnX;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel7;
      public static javax.swing.JLabel lblParkingLocation;
      private javax.swing.JPanel popContent;
      // End of variables declaration//GEN-END:variables
      public void mouseHover(JPanel p, JLabel l) {
            //entered
            l.setForeground(Color.WHITE);
            p.setBackground(new Color(233, 87, 63));
      }
      public void mouseHover(JLabel l, JPanel p) {
            //exit
            l.setForeground(Color.WHITE);
            p.setBackground(new Color(51, 51, 51));
      }
}
