/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finalsLab;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author alecco
 */
public class LinkedListGUI extends javax.swing.JFrame {
            LinkedList<String> l = new LinkedList<String>();

      public LinkedListGUI() {
            initComponents();
                        lblDoes.setVisible(false);
                        lblDoesNot.setVisible(false);
                        lblGet.setVisible(false);
                        lblSet.setVisible(false);
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            Addings = new javax.swing.ButtonGroup();
            container = new javax.swing.JPanel();
            pnlMain = new javax.swing.JPanel();
            jButton1 = new javax.swing.JButton();
            pnlLinkedList = new javax.swing.JPanel();
            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            txtAddInput = new javax.swing.JTextField();
            txtRemove = new javax.swing.JTextField();
            jButton7 = new javax.swing.JButton();
            jButton8 = new javax.swing.JButton();
            jButton9 = new javax.swing.JButton();
            jButton10 = new javax.swing.JButton();
            txtSearch = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jButton6 = new javax.swing.JButton();
            lblGetResult = new javax.swing.JLabel();
            lblDoes = new javax.swing.JLabel();
            lblElement = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jButton11 = new javax.swing.JButton();
            lblSize = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            txtGetInput = new javax.swing.JTextField();
            lblDoesNot = new javax.swing.JLabel();
            lblGet = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            txtSetInput = new javax.swing.JTextField();
            jButton12 = new javax.swing.JButton();
            jButton13 = new javax.swing.JButton();
            lblSetResult = new javax.swing.JLabel();
            lblSet = new javax.swing.JLabel();
            jButton14 = new javax.swing.JButton();
            txtFieldDisplay = new javax.swing.JTextField();
            jButton15 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            container.setLayout(new java.awt.CardLayout());

            pnlMain.setBackground(new java.awt.Color(0, 0, 0));
            pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jButton1.setBackground(new java.awt.Color(255, 255, 255));
            jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
            jButton1.setText("LinkedList");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            pnlMain.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, 50));

            container.add(pnlMain, "card2");

            jPanel1.setBackground(new java.awt.Color(51, 51, 51));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("LINKED LIST");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 330, 40));

            jButton2.setBackground(new java.awt.Color(255, 255, 255));
            jButton2.setText("<");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

            jButton3.setText("ADD LAST");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 92, 90, -1));

            jButton4.setText("ADD FIRST");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 92, 90, -1));

            jButton5.setText("ADD");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 92, 90, -1));

            jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Remove Element / Index:");
            jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, -1));

            txtAddInput.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        txtAddInputMouseClicked(evt);
                  }
            });
            txtAddInput.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtAddInputActionPerformed(evt);
                  }
            });
            jPanel1.add(txtAddInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 270, -1));

            txtRemove.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        txtRemoveMouseClicked(evt);
                  }
            });
            txtRemove.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtRemoveActionPerformed(evt);
                  }
            });
            jPanel1.add(txtRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

            jButton7.setText("REMOVE LAST");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton7ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 140, 135, -1));

            jButton8.setText("REMOVE ELEMENT");
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton8ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 192, 135, -1));

            jButton9.setText("SET");
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton9ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 100, -1));

            jButton10.setText("REMOVE FIRST");
            jButton10.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton10ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 135, -1));

            txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        txtSearchMouseClicked(evt);
                  }
            });
            txtSearch.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtSearchActionPerformed(evt);
                  }
            });
            jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 270, 135, -1));

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Input String:");
            jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

            jButton6.setText("SEARCH");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton6ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 290, 135, -1));

            lblGetResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblGetResult.setForeground(new java.awt.Color(204, 255, 51));
            lblGetResult.setText(" ");
            jPanel1.add(lblGetResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 415, 90, 20));

            lblDoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblDoes.setForeground(new java.awt.Color(204, 255, 51));
            lblDoes.setText("LinkedList DOES contain the Element:");
            jPanel1.add(lblDoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 320, 240, 20));

            lblElement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblElement.setForeground(new java.awt.Color(204, 255, 51));
            jPanel1.add(lblElement, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, 20));

            jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("Input Element to Search:");
            jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 160, -1));

            jButton11.setText("REMOVE INDEX");
            jButton11.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton11ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 215, 135, -1));

            lblSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblSize.setForeground(new java.awt.Color(255, 255, 51));
            lblSize.setText(" ");
            jPanel1.add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 360, 90, -1));

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("Input Index of Element to Get:");
            jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, -1));
            jPanel1.add(txtGetInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 60, -1));

            lblDoesNot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblDoesNot.setForeground(new java.awt.Color(204, 255, 51));
            lblDoesNot.setText("LinkedList DOES NOT contain the Element:");
            jPanel1.add(lblDoesNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 270, 20));

            lblGet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblGet.setForeground(new java.awt.Color(204, 255, 51));
            lblGet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lblGet.setText("Element returned by get(): ");
            jPanel1.add(lblGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, 170, 20));

            jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setText("Input Element to Set:");
            jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 130, -1));
            jPanel1.add(txtSetInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 60, -1));

            jButton12.setText("CHECK LIST SIZE");
            jButton12.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton12ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 135, -1));

            jButton13.setText("GET");
            jButton13.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton13ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 100, -1));

            lblSetResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblSetResult.setForeground(new java.awt.Color(204, 255, 51));
            lblSetResult.setText(" ");
            jPanel1.add(lblSetResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, 20));

            lblSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblSet.setForeground(new java.awt.Color(204, 255, 51));
            lblSet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lblSet.setText("Linked list after change: ");
            jPanel1.add(lblSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 20));

            jButton14.setText("DISPLAY LIST");
            jButton14.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton14ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 240, 30));

            txtFieldDisplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            txtFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jPanel1.add(txtFieldDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 360, 70));

            jButton15.setText("CLEAR");
            jButton15.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton15ActionPerformed(evt);
                  }
            });
            jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 120, 30));

            javax.swing.GroupLayout pnlLinkedListLayout = new javax.swing.GroupLayout(pnlLinkedList);
            pnlLinkedList.setLayout(pnlLinkedListLayout);
            pnlLinkedListLayout.setHorizontalGroup(
                  pnlLinkedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            pnlLinkedListLayout.setVerticalGroup(
                  pnlLinkedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            );

            container.add(pnlLinkedList, "card3");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setBounds((screenSize.width-416)/2, (screenSize.height-638)/2, 416, 638);
      }// </editor-fold>//GEN-END:initComponents

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            container.removeAll();
            container.add(pnlLinkedList);
            repaint();
            revalidate();
      }//GEN-LAST:event_jButton1ActionPerformed

      private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            container.removeAll();
            container.add(pnlMain);
            repaint();
            revalidate();
      }//GEN-LAST:event_jButton2ActionPerformed

      private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            l.addFirst(txtAddInput.getText());
            txtAddInput.setText("");
      }//GEN-LAST:event_jButton4ActionPerformed

      private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            l.add(txtAddInput.getText());
            txtAddInput.setText("");
      }//GEN-LAST:event_jButton5ActionPerformed

      private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            l.addLast(txtAddInput.getText());
            txtAddInput.setText("");
      }//GEN-LAST:event_jButton3ActionPerformed

      private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            l.removeFirst();
      }//GEN-LAST:event_jButton7ActionPerformed

      private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            boolean status = l.contains(txtRemove.getText());
                  if (status)
                        l.remove(txtRemove.getText());
                  else
                        JOptionPane.showMessageDialog(null, "LinkedList does not contain "+txtRemove);
      }//GEN-LAST:event_jButton8ActionPerformed

      private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            lblSet.setVisible(true);
            String x = (txtSetInput.getText());
            int in = Integer.parseInt(txtGetInput.getText());
            lblSetResult.setText(""+l.set(in,x));
            
            txtAddInput.setText("");
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            lblGet.setVisible(false);
            lblGetResult.setText("");
      }//GEN-LAST:event_jButton9ActionPerformed

      private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
            l.removeFirst();
      }//GEN-LAST:event_jButton10ActionPerformed

      private void txtAddInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddInputActionPerformed

            
            txtFieldDisplay.setText("");
      }//GEN-LAST:event_txtAddInputActionPerformed

      private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            boolean status = l.contains(txtSearch.getText());
            lblSize.setText("");
                  if (status){
                        lblDoes.setVisible(true);
                        lblElement.setText(txtSearch.getText());
                  }else{
                        lblGetResult.setVisible(true);
                        lblElement.setText(txtSearch.getText());
                  }
                  
      }//GEN-LAST:event_jButton6ActionPerformed

      private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
            txtRemove.setText("");
            txtAddInput.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
            txtFieldDisplay.setText("");

      }//GEN-LAST:event_txtSearchMouseClicked

      private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            try{
                  int x = Integer.parseInt(txtRemove.getText());
            l.remove(x);
            }catch (Exception e){
                  JOptionPane.showMessageDialog(null, "Please enter an Integer for the Index");
            }
      }//GEN-LAST:event_jButton11ActionPerformed

      private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            lblSize.setText("Size of List: "+l.size());
            txtAddInput.setText("");
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
            txtFieldDisplay.setText("");

      }//GEN-LAST:event_jButton12ActionPerformed

      private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
            lblGet.setVisible(true);
            int in = Integer.parseInt(txtGetInput.getText());
            lblGetResult.setText(""+l.get(in));
            
            txtAddInput.setText("");
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            lblSet.setVisible(false);
            lblSetResult.setText("");
            txtFieldDisplay.setText("");
      }//GEN-LAST:event_jButton13ActionPerformed

      private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
            txtFieldDisplay.setText(""+l);
            
            lblSize.setText("");
            txtAddInput.setText("");
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
      }//GEN-LAST:event_jButton14ActionPerformed

      private void txtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemoveActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_txtRemoveActionPerformed

      private void txtAddInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddInputMouseClicked
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            lblSize.setText("");
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
      }//GEN-LAST:event_txtAddInputMouseClicked

      private void txtRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRemoveMouseClicked
            txtAddInput.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
      }//GEN-LAST:event_txtRemoveMouseClicked

      private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_txtSearchActionPerformed

      private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            txtAddInput.setText("");
            txtRemove.setText("");
            txtSearch.setText("");
            
            lblDoes.setVisible(false);
            lblDoesNot.setVisible(false);
            lblElement.setText("");
            lblSize.setText("");
            
            lblGet.setVisible(false);
            lblSet.setVisible(false);
            lblGetResult.setText("");
            lblSetResult.setText("");
            txtFieldDisplay.setText("");
      }//GEN-LAST:event_jButton15ActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Windows".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(LinkedListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(LinkedListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(LinkedListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(LinkedListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new LinkedListGUI().setVisible(true);
                  }
            });
      }
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.ButtonGroup Addings;
      private javax.swing.JPanel container;
      private javax.swing.JButton jButton1;
      private javax.swing.JButton jButton10;
      private javax.swing.JButton jButton11;
      private javax.swing.JButton jButton12;
      private javax.swing.JButton jButton13;
      private javax.swing.JButton jButton14;
      private javax.swing.JButton jButton15;
      private javax.swing.JButton jButton2;
      private javax.swing.JButton jButton3;
      private javax.swing.JButton jButton4;
      private javax.swing.JButton jButton5;
      private javax.swing.JButton jButton6;
      private javax.swing.JButton jButton7;
      private javax.swing.JButton jButton8;
      private javax.swing.JButton jButton9;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JLabel lblDoes;
      private javax.swing.JLabel lblDoesNot;
      private javax.swing.JLabel lblElement;
      private javax.swing.JLabel lblGet;
      private javax.swing.JLabel lblGetResult;
      private javax.swing.JLabel lblSet;
      private javax.swing.JLabel lblSetResult;
      private javax.swing.JLabel lblSize;
      private javax.swing.JPanel pnlLinkedList;
      private javax.swing.JPanel pnlMain;
      private javax.swing.JTextField txtAddInput;
      private javax.swing.JTextField txtFieldDisplay;
      private javax.swing.JTextField txtGetInput;
      private javax.swing.JTextField txtRemove;
      private javax.swing.JTextField txtSearch;
      private javax.swing.JTextField txtSetInput;
      // End of variables declaration//GEN-END:variables
}
